### ISSUE TITLE
Feedback: QT clustering

### ISSUE THREAD

**Issue by jakobnissen** [MichaelSev/Julia#7]
So I've been taking a look at your code. It's really good. But I still have a lot of smaller issues.

In the spirit of Kent Beck, my feedback will be in the three phases of software development: Make it work, make it right, make it fast.

## Make it work.
Of course, your code should give the right answer, otherwise it's useless. So... does it? It *looks* good to me. But should you really trust mine or your own intuition? The problem with clustering is that it's hard to calculate it by hand to verify it works correctly.

Much better would be to get hold of a reference implementation, or the true answer for some dataset. Then you can check it works.

Even better would be to write *unit tests*. These are automated tests you can run that will run your code and compare with some known result. For example, you can write a script that executes your code on the 1000 points, then compares the result to the true result and prints if they are different. Unit tests and git work synergistically - after every commit, you run your unit tests. If the tests fail, you change your code. And if they keep failing, you can always just use git to revert to the last commit.

Julia has the stansdard library module "Test" exactly for this purpose, but if you don't want to learn that, you can just write your own script.

## Make it right
After working correctly, the next thing to make sure is that you have the right algorithm. This QT problem is excellent because there is so many tweaks you can do to the algorithm to make it faster. You have already done several:
* You create potential clusters with only the relevant clusters for each seed
* In the `make_candidatecluster` function, you keep removing points as they become irrelevant for the current cluster.
* When updating the distance in `make_candidatecluster`, you only check if the distance to the newly included point is larger. That's pretty neat!

There are a few more optimizations you could do. I won't spoil too much, but:
* Say there are points A, B, C, D, E, and F close together in space. When calculating the candidate cluster for A, points B-F will be included as the first 5 points. When calculating the candidate cluster B, the same 5 will be included. And similar for the others. That means the 7th point in the cluster MUST be the same for all 7 seeds. So here you are duplicating work. You can build a cache to keep track of clusters you have already built.
* In fact, even after outputting a cluster, most of the other clusters will not change, so you can just keep them in memory, and remove the ones that are no longer valid.

## Make it fast
There are a LOT of low-level optimizations you could do. I'll do a code review with all these small things. Perhaps it could make your code 3x faster, let's see. But these things are much less important than correctness and tweaking the algorithm!

For reference, I digged up my own solution when I did the Python course in 2015 - on 1000 points, my old Python code took 23 seconds and your takes 0.5 seconds, so you're already way ahead :)

**Comment by MichaelSev** [comment]
Hej Jakob

I agree in all the optimization points under "make it right", the plan is to get them implemented as time goes :) 
Peter has now uploaded another solution on the teaching page, and those are also identical :) 

About the code in comments: 
I agree defineatly about the rounding, this was just for my own fault when, when i was visual expecting the output. Those will be removed. 

Smart trick with the foorloop for distancematrix, had not thought about that!

The last part will also be made in a function, the same goes for the output. 

About the overwriting in array and pop/push. 
I have considered inserting arrays of zeros (because those are never used as index) 
But the problem was that I did not know for sure how long it would be. 

I do know for sure it will never be longer that the number of elements in "whitelist" (or the size of the dataset). 
Then there should also be a counter to keep track of how much of the array there is used? 

Would that still be more effective with those long vectors, or should there be considered another method?

**Comment by MichaelSev** [comment]
Forget the last part, I think, that I have found a good solution, since it can never extend the number of items in the "potential cluster list" which contain which points to look at. :)
